# Site settings
title: IX Workshop da Genética
description: "Mini-cursos"
url: "http://cristianetaniguti.github.io/Workshop_genetica_2015/"
author:
  name: "Jacopo Rabolini"
  email: "hello@jacoporabolini.com"
  url: "http://cristianetaniguti.github.io/"

# Build settings
baseurl: /Workshop_genetica_2015/ # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: true
reverse: false
